## Analyzing PEMA home ranges
# This script contains analysis of the home ranges of PEMA captured >4x as adults across all NEON sites. 
# Inputs: 'ao_ranges' dataframe as generated by 'get_home_ranges' script.

##### Load libraries
library(ggplot2)
library(dplyr)
library(car)
library(lme4)
library(ggnewscale)
library(ggpubr)

###### Looking at ao_ranges
# summary(ao_ranges) # for most analyses, has best sample size
# 
# # boxplots of categorical vars
# boxplot(UD ~ sex, ao_ranges)
# boxplot(UD ~ site, ao_ranges)
# boxplot(UD ~ vegType, ao_ranges)
# boxplot(UD ~ year, ao_ranges)
# 
# # scatterplots of numerical vars
# plot(UD ~ meanMNKA, ao_ranges)
# plot(UD ~ latitude, ao_ranges)
# plot(UD ~ bodyCondition, ao_ranges)

##### Modeling home range vs. environmental and intrinsic factors
# build model
hr.fit=glmer(UD ~ as.factor(sex) * as.factor(vegType) * meanMNKA * latitude * bodyCondition + 
            (1 | year) + (1 | site), ao_ranges)
# view outputs
Anova(hr.fit)


##### Visualizing HR vs. factors by sex
### HR v. Sex
hr.sex<-ggplot(ao_ranges, aes(x=sex, y=UD, fill=sex, color=sex)) +
  ggtitle("Home Range by Sex") +
  xlab("Sex") +
  ylab(expression("Home Range Area (m"^2*")")) +
  geom_boxplot() +
  scale_x_discrete(labels=c('Female','Male')) +
  scale_fill_manual(values=c("#ED8612", "#1279ED")) +
  scale_color_manual(values=c("#7f480a", "#093f7b")) +
  theme(legend.position="none",
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'))

### HR v. vegType
hr.vegType<-ggplot() +
  ggtitle("Home Range by Sex") +
  xlab("Habitat Type") +
  ylab(expression("Home Range Area (m"^2*")")) +
  geom_boxplot(data = ao_ranges,
             aes(x=vegType, y=UD, color=sex, fill=sex),
             alpha=0.65) +
  scale_fill_manual(values=c("#ED8612", "#1279ED")) +
  scale_color_manual(values=c("#7f480a", "#093f7b")) +
  theme(legend.position="none",
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'))

  
### for all scatter plots, shape = sex
### HR v. MNKA (Fig 1)
hr.mnka<-function(female,male,alpha){
ggplot(ao_ranges, aes(x=meanMNKA, y=UD, color=sex, fill=sex, shape=sex)) +
  ggtitle("Home Range vs. Population Density") +
    xlab("Population Density (Mean MNKA of Adult Captures)") +
    ylab(expression("Home Range Area (m"^2*")")) +
  geom_point(size = 4, alpha=alpha) +
  geom_smooth(method = 'glm', se=TRUE, fullrange=TRUE, size=2) +
  scale_color_manual(labels=c('Female','Male'),values=c(female, male)) +
  scale_fill_manual(labels=c('Female','Male'),values=c(female, male)) +
  scale_shape_manual(labels=c('Female','Male'),values=c('circle','triangle')) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
    theme(panel.background = element_blank(),
          axis.line = element_line(colour = "black"),
          axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
          axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
          axis.text = element_text(size=15),
          plot.title = element_text(size = 22, face='bold'),
          legend.position = c(0.8,0.87),
          legend.text = element_text(size = 20),
          legend.title = element_blank(),
          legend.key = element_rect(fill = 'white'),
          legend.key.height = unit(1,'cm'),
          legend.background = element_rect(fill = 'white',color = 'black'))
}

# hr.mnka(female='#E95020', male='#304A73',alpha=0.6)
# hr.mnka(female='#D66A00', male='#006CD6',alpha=0.65) #'clay'orange4

hr.mnka1<-hr.mnka(female='#ED8612', male='#1279ED',alpha=0.65) # noa likes this too

### HR v. bodyCondition (Fig 2)
hr.bc<-function(female,male,alpha){
  ggplot(ao_ranges, aes(x=bodyCondition, y=UD, color=sex, fill=sex, shape=sex),
       alpha=0.1) +
  ggtitle("Home Range vs. Body Condition") +
  xlab("Body Condition") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  geom_point(size = 4, alpha=alpha) +
  geom_smooth(method='glm',se=TRUE, fullrange=TRUE, size=2, alpha=0.3) +
  scale_fill_manual(labels=c('Female','Male'),
                    values=c(female, male)) +
  scale_color_manual(labels=c('Female','Male'),
                     values=c(female, male)) +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.82,0.75),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))
}

# hr.bc(female='#E95020', male='#304A73',alpha=0.6)
# hr.bc(female="#EF815F", male="#6487be",alpha=0.7)

hr.bc1<-hr.bc(female='#ED8612', male='#1279ED',alpha=0.65) # noa likes this too


# HR v. latitude
hr.lat<-function(female,male,alpha){
  ggplot(ao_ranges, aes(x=latitude, y=UD, fill=sex, color=sex, shape=sex)) +
  ggtitle("Home Range vs. Latitude") +
  xlab("Latitude") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  geom_point(size = 4, alpha=alpha) +
  geom_smooth(method='glm',se=TRUE, fullrange=TRUE, size=2) +
  scale_fill_manual(labels=c('Female','Male'),
                      values=c(female, male)) +
  scale_color_manual(labels=c('Female','Male'),
                     values=c(female, male)) +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
    guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.14,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))
}

hr.lat1<-hr.lat(female='#ED8612', male='#1279ED',alpha=0.65) # noa likes this too


### Multi-panel of single vars (split by sex)
ggarrange(hr.mnka1,hr.bc1,hr.lat1,hr.vegType,ncol=2,nrow=2)

### 2-var plots
# HR v. bC color split by sex, gradient for latitude
hr.bC.2lat.grad<-ggplot() +
  geom_point(data = filter(ao_ranges, sex == "F"),
             aes(x=bodyCondition, y=UD, shape=sex,
                 color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, sex == "F"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#ED8612',fill='#fbe5cb') +
  scale_color_gradient(name = 'Latitude',
                       high = "#ED8612",
                       low = "#fbe5cb",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  new_scale_color() +
  geom_point(data = filter(ao_ranges, sex == "M"),
             aes(x=bodyCondition, y=UD, shape=sex, color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, sex == "M"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#1279ED',fill='#cae1fb') +
  scale_color_gradient(name = 'Latitude',
                       high = "#1279ED",
                       low = "#cae1fb",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Home Range vs. Body Condition") +
  xlab("Body Condition") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'right')


# HR v. bC, gradient for latitude
hr.bC.1lat.grad<-ggplot(ao_ranges, aes(x=bodyCondition, y=UD, color=latitude, shape=sex)) +
  ggtitle("Home Range vs. Body Condition") +
  xlab("Body Condition") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  geom_point(size = 4, alpha=0.7) +
  geom_smooth(method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#2c216a', fill='#d0cbef', aes(linetype = sex)) +
  scale_color_gradient(name = 'Latitude',
                       high = "#2c216a",
                       low = "#d0cbef",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(name='Sex',
                     labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  scale_linetype_manual(name='Sex',
                        labels=c('Female','Male'),
                        values=c('solid','longdash')) +
  # guides(color_gradient = guide_legend(order = 1),
  #        shape = guide_legend(order = 2)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'right',
        # legend.text = element_text(size = 15),
        # legend.title = element_text(size = 15),
        # legend.key = element_rect(fill = 'white'),
        # legend.key.height = unit(0.65,'cm'),
        # legend.background = element_rect(fill = 'white',color = 'black')
        )

# HR v. latitude, color split by sex, gradient for bC
hr.lat.2bC.grad<-ggplot() +
  geom_point(data = filter(ao_ranges, sex == "F"),
             aes(x=latitude, y=UD, shape=sex,
                 color=bodyCondition),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, sex == "F"),
              mapping = aes(x=latitude, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#ED8612',fill='#fbe5cb') +
  scale_color_gradient(name = 'Body Condition',
                       high = "#ED8612",
                       low = "#fbe5cb",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  new_scale_color() +
  geom_point(data = filter(ao_ranges, sex == "M"),
             aes(x=latitude, y=UD, shape=sex, color=bodyCondition),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, sex == "M"),
              mapping = aes(x=latitude, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#1279ED',fill='#cae1fb') +
  scale_color_gradient(name = 'Body Condition',
                       high = "#1279ED",
                       low = "#cae1fb",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Home Range vs. Latitude") +
  xlab("Latitude") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        legend.position='none',
        plot.title = element_text(size = 22, face='bold'))

# HR v. latitude, gradient for bC
hr.lat.1bC.grad<-ggplot(ao_ranges, aes(x=latitude, y=UD, color=bodyCondition, shape=sex)) +
  ggtitle("Home Range vs. Latitude") +
  xlab("Latitude") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  geom_point(size = 4, alpha=0.7) +
  geom_smooth(method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#2c216a', fill='#d0cbef', aes(linetype = sex)) +
  scale_color_gradient(name = 'Body Condition',
                       high = "#2c216a",
                       low = "#d0cbef",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(name='Sex',
                     labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  scale_linetype_manual(name='Sex',
                        labels=c('Female','Male'),
                        values=c('solid','longdash')) +
  # guides(color_gradient = guide_legend(order = 1),
  #        shape = guide_legend(order = 2)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'none',
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(0.65,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))


### Multi-panel w/ 2-var plots
ggarrange(hr.lat.2bC.grad,hr.bC.2lat.grad,
          hr.lat.1bC.grad,hr.bC.1lat.grad,
          ncol=2,nrow=2)

# Scatter plot HR(y axis) by body condition (x axis)
# with sex as shape (e.g. males squares, females circles)
# veg type as color, and latitude as color gradient within each veg type.
#For example, if forests are green, then low latitudes would be light green
# and high latitudes would be dark green. Then if grasses are gold, low
# latitude would be light gold and high ones would be dark gold
ggplot() +
  geom_point(data = filter(ao_ranges, vegType == "forest"),
             aes(x=bodyCondition, y=UD, shape=sex,
                 color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "forest"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#296732',fill='#9bd7a3') +
  scale_color_gradient(name = 'Forest Lat.',
                       high = "#296732",
                       low = "#9bd7a3",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  new_scale_color() +
  geom_point(data = filter(ao_ranges, vegType == "grassland"),
             aes(x=bodyCondition, y=UD, shape=sex, color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "grassland"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#c19c03',fill='#feeeab') +
  scale_color_gradient(name = 'Grassland Lat.',
                       high = "#c19c03",
                       low = "#feeeab",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  new_scale_color() +
  geom_point(data = filter(ao_ranges, vegType == "shrubland"),
             aes(x=bodyCondition, y=UD, shape=sex, color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "shrubland"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#2c216a',fill='#bfb7e9') +
  scale_color_gradient(name = 'Shrubland Lat.',
                       high = "#2c216a",
                       low = "#bfb7e9",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Home Range vs. Body Condition") +
  xlab("Body Condition") +
  ylab(expression("Home Range Area (m"^2*")")) +
  #ylim(c(0,8000)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'))


### HR v. bC, shape = sex, split by vegType into sub-plots
# forest
forest<-ggplot() +
  geom_point(data = filter(ao_ranges, vegType == "forest"),
             aes(x=bodyCondition, y=UD, shape=sex,
                 color=latitude),
             alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "forest"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#296732',fill='#9bd7a3') +
  scale_color_gradient(name = 'Forest Lat.',
                       high = "#296732",
                       low = "#9bd7a3",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Forest") +
  xlab("Body Condition") + ylab("Home Range (50% UD)") +
  ylim(c(0,10250)) +
  scale_x_continuous(breaks=c(-5,0,5,10),
                     limits=c(-6.2,11)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'none')
# grassland
grassland<-ggplot() + 
  geom_point(data = filter(ao_ranges, vegType == "grassland"),
           aes(x=bodyCondition, y=UD, shape=sex, color=latitude),
           alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "grassland"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#c19c03',fill='#feeeab') +
  scale_color_gradient(name = 'Grassland Lat.',
                       high = "#c19c03",
                       low = "#feeeab",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Grassland") +
    xlab("Body Condition") + ylab("Home Range (50% UD)") +
  ylim(c(0,10250)) +
  scale_x_continuous(breaks=c(-5,0,5,10),
                     limits=c(-6.2,11)) +
    theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'none')
# shrubland
shrubland<-ggplot() +
  geom_point(data = filter(ao_ranges, vegType == "shrubland"),
                      aes(x=bodyCondition, y=UD, shape=sex, color=latitude),
                      alpha=0.7, size=4) +
  geom_smooth(data = filter(ao_ranges, vegType == "shrubland"),
              mapping = aes(x=bodyCondition, y=UD),
              method='glm',se=TRUE, fullrange=TRUE, size=2,
              color='#2c216a',fill='#bfb7e9') +
  scale_color_gradient(name = 'Latitude',
                       high = "#2c216a",
                       low = "#bfb7e9",
                       space = "Lab",
                       guide = "colourbar",
                       aesthetics = "color") +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  ggtitle("Shrubland") +
  xlab("Body Condition") + ylab("Home Range (50% UD)") +
  ylim(c(0,10250)) +
  scale_x_continuous(breaks=c(-5,0,5,10),
                     limits=c(-6.2,11)) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = 'none')

# set for 1 row of 3 plots
horiz.vegTypes<-ggarrange(forest,grassland,shrubland,ncol=3)

vert.vegTypes<-ggarrange(forest,grassland,shrubland,ncol=1)


# 
# ### boxplot instead?
# ggplot() +
#   geom_jitter(data = ao_ranges, aes(x=vegType, y=UD, color = latitude,
#                                     shape = sex, size = bodyCondition)) +
#   scale_color_gradient(name = 'Latitude',
#                        high = '#e5682d',
#                        low = '#0a7b02') +
#   ggtitle("Home Range by everything") +
#   xlab("Habitat Type") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))
# 
#   
# #
# ggplot() +
#   geom_jitter(data = ao_ranges, aes(x=vegType, y=UD, color = latitude,
#                                     shape = sex, size = bodyCondition)) +
#   scale_color_gradient(name = 'Latitude',
#                        high = '#362981',
#                        low = '#bfb7f0')  +
#   ggtitle("Home Range by everything") +
#   xlab("Habitat Type") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))
# 
# 
# 
# 
# #
# ggplot() +
#   geom_jitter(data = filter(ao_ranges, sex == 'M'),
#               aes(x=vegType, y=UD, color = latitude,
#                   size = bodyCondition)) +
#   scale_color_gradient(name = 'Lat. of\nMales',
#                        high = '#362981',
#                        low = '#bfb7f0') +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, sex == 'F'),
#               aes(x=vegType, y=UD, color = latitude,
#                   size = bodyCondition)) +
#   scale_color_gradient(name = 'Lat. of\nFemales',
#                        high = '#298131',
#                        low = '#baf0b7') +
#   ggtitle("Home Range by everything") +
#   xlab("Habitat Type") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))
#   
# 
# #
# ggplot() +
#   geom_jitter(data = filter(ao_ranges, sex == 'M'),
#               aes(x=vegType, y=UD, color = latitude,
#                   size = bodyCondition)) +
#   scale_color_gradient(name = 'Lat. of\nMales',
#                        high = '#362981',
#                        low = '#bfb7f0') +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, sex == 'F'),
#               aes(x=vegType, y=UD, color = latitude,
#                   size = bodyCondition)) +
#   scale_color_gradient(name = 'Lat. of\nFemales',
#                        high = '#b78b0c',
#                        low = '#f8d95e') +
# ggtitle("Home Range by everything") +
#   xlab("Habitat Type") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))
# 
# 
# 
# 
# 
# 
# #
# ggplot() +
#   geom_jitter(data = filter(ao_ranges, vegType == "forest"),
#               aes(x=sex, y=UD, color=latitude, size=bodyCondition,
#                   interaction=c(sex,vegType))) +
#   scale_color_gradient(name = 'Shrubland Lat.',
#                        high = "#2c216a",
#                        low = "#bcbddc",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, vegType == "forest"),
#              aes(x=sex, y=UD, color=latitude, size=bodyCondition)) +
#   scale_color_gradient(name = 'Forest Lat.',
#                        high = "#296732",
#                        low = "#57c867",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, vegType == "forest"),
#               aes(x=sex, y=UD, color=latitude, size=bodyCondition)) +
#   scale_color_gradient(name = 'Grassland Lat.',
#                        high = "#c19c03",
#                        low = "#fadd63",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   ggtitle("Home Range vs. Body Condition") +
#   xlab("Body Condition") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))
# 
# 
# 
# # Maybe boxplots separated by sex & vegType
# # w/ jittered points sized by bodyCondition, color gradient by lat?
# ggplot(data = ao_ranges, aes(x=vegType,y=UD,fill=sex)) +
#   geom_boxplot(outlier.shape = NA) +
#   geom_point(shape = 21, alpha = 0.5, position=position_jitterdodge())
#   
# #
# my_dat <- data.frame(class=factor(rep(1:2, 600)),
#                      y=rnorm(1200),
# x=rep(letters[1:3], each=400))
# 
# ggplot(my_dat, aes(x=x, y=y, fill=class, color=class)) +
#   geom_boxplot(outlier.shape = NA) +
#   geom_point(shape = 21, alpha = 0.5, position=position_jitterdodge()) +
#   scale_fill_manual(values = rep(NA, 2)) 
# 
# 
#   
#   
#   
# #
#   geom_boxplot(data = ao_ranges,
#                aes(x=vegType, dodge=sex))
#   geom_jitter(data = ao_ranges,
#               aes(x=ve, y=UD, color=latitude, size=bodyCondition)) +
#   scale_color_gradient(name = 'Shrubland Lat.',
#                        high = "#2c216a",
#                        low = "#bcbddc",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, vegType == "forest"),
#               aes(x=sex, y=UD, color=latitude, size=bodyCondition)) +
#   scale_color_gradient(name = 'Forest Lat.',
#                        high = "#296732",
#                        low = "#57c867",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   new_scale_color() +
#   geom_jitter(data = filter(ao_ranges, vegType == "forest"),
#               aes(x=sex, y=UD, color=latitude, size=bodyCondition)) +
#   scale_color_gradient(name = 'Grassland Lat.',
#                        high = "#c19c03",
#                        low = "#fadd63",
#                        space = "Lab",
#                        guide = "colourbar",
#                        aesthetics = "color") +
#   ggtitle("Home Range vs. Body Condition") +
#   xlab("Body Condition") + ylab("Home Range (50% UD)") +
#   ylim(c(0,8000)) +
#   theme(panel.background = element_blank(),
#         axis.line = element_line(colour = "black"),
#         axis.title.x = element_text(size = 20, margin = margin(t=14,r=0,b=0,l=0)),
#         axis.title.y = element_text(size = 20, margin = margin(t=0,r=14,b=0,l=0)),
#         axis.text = element_text(size=15),
#         plot.title = element_text(size = 22, face='bold'))

